<!doctype html>
<html class="no-js" lang="">

<head>
  <meta charset="utf-8">
  <title>newrelic-winston-enricher-repo</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta name="theme-color" content="#fafafa">
</head>

<body>

  <p>Hello world! This is HTML5 Boilerplate.</p>
  <!-- <script src="js/app.js"></script> -->
</body>

</html>